import React from "react";
import PageWrapper from "../../shared/PageWrapper/PageWrapperComponent";

const ApplicationViewComponent = () => (
  <PageWrapper title="My Application">
    <div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
      <div>wegwgweg</div>
    </div>
  </PageWrapper>
);

export default ApplicationViewComponent;
